name: 'Test'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: 'Run Tests 🧪'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: |
          npm ci
          npm run build
      - uses: mattallty/jest-github-action@v1
        env:
          # This is to support ESM during jest runs
          NODE_OPTIONS: --experimental-vm-modules
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          coverage-comment: false
